### ISSUE TITLE
Model Templates As Part of Project

### ISSUE THREAD

**Issue by sherl0cks** [rht-labs/ansible-stacks#93]
This feature will model templates as part of a project, not as an application. The current model is built around that applications are driven by `oc new-app`, and thus merging these two concepts is leading to conflicts as seen with #89 #88 #80. Modelling templates as part of a project allows use to clearly separate concerns in our model, as well as our implementation.

**Comment by etsauer** [comment]
This makes sense. I've actually been thinking about using templates + ansible-stacks as a tool for promoting config changes through environments. In order to do that, we would have to move away from using `oc new-app` in instantiate the template, and instead use something along the lines of `oc process -f <template> | oc {create,replace} -f-`. I can take this on in the next couple of weeks.

**Comment by sherl0cks** [comment]
@etsauer good to hear. there are a slew of options if we decouple. I started down the path of `oc process` but I skipped it in favor of `oc new-app --template`. That said, I think if we get this early impl in, it'll be much easier / safer to extend than messing with other bits of automation

**Comment by etsauer** [comment]
Yeah, I think in general designing around `oc create/replace` is a better
long term solution as it provides a lot of flexibility. Then couple that
with the ability to process a parameterized template into the things I want
to create/replace, and it's very powerful.

**Comment by etsauer** [comment]
@sherl0cks Yeah, I think in general designing around `oc create/replace` is a better long term solution as it provides a lot of flexibility. Then couple that with the ability to process a parameterized template into the things I want to create/replace, and it's very powerful.

**Comment by sherl0cks** [comment]
@etsauer agreed. let's get this initial bit committed, and then open some tickets on where we go long term.

**Comment by etsauer** [comment]
so @sherl0cks, per https://github.com/rht-labs/ansible-stacks/pull/77#issuecomment-273848717 we're introducing the concept of an `overwrite` parameter for a secret. I could see us needing something similar for handling whether we issue a `create` or `replace` on a template object. Are you ok with including that in the model or is there something else you prefer?

**Comment by sherl0cks** [comment]
@etsauer I think it's a good idea, but I want to treat it as a second step. I need to first focus on having a strong foundation that is well tested. Once that is in place (should be end of day), then I think there are a long list of ways to enhance it. 

In part, this is driven by the small window I have to make said changes before travel & PTO.

**Comment by sherl0cks** [comment]
@etsauer also worth noting that part of that strong foundation is a way to handle idempotency, which can then be leveraged for something like overwrite

**Comment by sherl0cks** [comment]
@etsauer take a look on the first drafts of this and let me know if this structure works for you

https://github.com/sherl0cks/ansible-stacks/blob/templates/roles/create-openshift-resources/tests/vars/jenkins_templates.json
https://github.com/sherl0cks/ansible-stacks/blob/templates/roles/create-openshift-resources/tests/cdk_create_jenkins_templates.yml
